fix(parse): solve remote and circular references
Swagger-parser resolves circular references with Object references. PathsParser does not handle this case and will result in an infinite loop.

fix(ajv-openapi)!: remove draft-04 support

To solve an error importing AJV when OpenAPI Mocker is used as API from another application, that is using higher versions of AJV
Error: Cannot find module 'ajv/lib/refs/json-schema-draft-04.json'
Require stack:
[private-path]/[app-using-open-api-mocker-with-higher-ajv-version]/node_modules/ajv-openapi/index.js
[private-path]/[app-using-open-api-mocker-with-higher-ajv-version]/node_modules/open-api-mocker/lib/schema-validator/index.js
[private-path]/[app-using-open-api-mocker-with-higher-ajv-version]/node_modules/open-api-mocker/lib/paths/path.js
[private-path]/[app-using-open-api-mocker-with-higher-ajv-version]/node_modules/open-api-mocker/lib/paths/parser.js
[private-path]/[app-using-open-api-mocker-with-higher-ajv-version]/node_modules/open-api-mocker/lib/paths/index.js
[private-path]/[app-using-open-api-mocker-with-higher-ajv-version]/node_modules/open-api-mocker/lib/open-api-mocker.js